### ISSUE TITLE
Changeset dump file contains no comments after February 23rd

### ISSUE THREAD

**Issue by ToeBee** [zerebubuth/planet-dump-ng#12]
I just added the ability to parse out changeset comments to [ChangesetMD](https://github.com/ToeBee/ChangesetMD). After the first run, @pnorman noticed that the resulting database had no changeset comments newer than February 23rd, 2015. I cracked open the dump file and it appears to be the dump file that is at fault, not my parsing. The last changeset with a comment in the dump file is [changeset 29033875](http://www.openstreetmap.org/changeset/29033875)

**Comment by zerebubuth** [comment]
Thanks for reporting this!

Looks like a fairly intricate bug... it's not obvious to me what's going wrong. I'll have to dig into it in more detail.

**Comment by zerebubuth** [comment]
This will be fixed by openstreetmap/chef#14 - it turns out it wasn't an intricate bug in planet-dump-ng at all, but in how I'd scripted it up to run. When the next planet is run, the changeset comments should all be present.

**Comment by zerebubuth** [comment]
I just checked `discussions-150615.osm.bz2`, and that looks to contain the discussions up to Sunday night. Thanks again for reporting this!
