### ISSUE TITLE
OSM AWS Athena Tables Not Updated

### ISSUE THREAD

**Issue by ojasgupta1** [zerebubuth/planet-dump-ng#27]
The OSM Athena Tables get updated every week on Sunday, but this week they didn't got updated, the planet-latest.orc was last updated on 5-June-2022.
https://s3.console.aws.amazon.com/s3/buckets/osm-pds?region=us-east-1&prefix=planet/&showversions=false

**Comment by zerebubuth** [comment]
Hi! Thanks for getting in touch. Unfortunately, I don't think I can help - the `planet-dump-ng` software is used for creating planet dump files from the OpenStreetMap server, and doesn't handle loading that anywhere else.

The [documentation for OSM on AWS](https://registry.opendata.aws/osm/) mentions Athena, so perhaps it's worth checking [their issues page](https://github.com/mojodna/osm-pds-pipelines/issues) to see if there's anything relevant?

Sorry I couldn't be more help.
