### ISSUE TITLE
No separate changesets file.

### ISSUE THREAD

**Issue by zerebubuth** [zerebubuth/planet-dump-ng#3]
Previous planet dumps also created a "changesets.osm" separately, for people who only wanted/needed the changesets. `planet-dump-ng` does not and, even though changesets are part of the XML dump, no-one wants to download 10s of GB to get at the 100s of MB of changesets.

**Comment by pnorman** [comment]
Is this something we want to have through planet-dump-ng or do through database queries?

I guess the main advantage to planet-dump-ng generation is it keeps the planet file and changesets file in sync.

Looking at this for the upcoming hack weekend - and adding changeset discussion dumps.

**Comment by zerebubuth** [comment]
Ooops, I should have updated this - I added changeset dumps in 5db08c39 back in March last year and they're available [on the planet dump site](http://planet.openstreetmap.org/planet/).

Adding changeset discussion dumps should be relatively straightforward - we can get them from the same database dump, but I'll add that as a separate issue.
