### ISSUE TITLE
v1.2.4 fails to compile on Debian 11

### ISSUE THREAD

**Issue by kresp0** [zerebubuth/planet-dump-ng#30]
Hi,

Installed all required dependencies on Debian 11 with apt and that worked fine. Both `./autogen.sh` and `./configure` also finished without errors. But `make` failed with this error:

```
Making all in src
make[1]: Entering directory '/usr/local/src/planet-dump-ng-1.2.4/src'
  CXX      changeset_filter.o
  CXX      changeset_map.o
  CXX      copy_elements.o
  CXX      dump_archive.o
  CXX      dump_reader.o
  CXX      extract_kv.o
  CXX      history_filter.o
  CXX      insert_kv.o
  CXX      output_writer.o
  CXX      pbf_writer.o
  CXX      planet-dump.o
  CXX      time_epoch.o
  CXX      types.o
  CXX      xml_writer.o
  CXXLD    ../planet-dump-ng
/usr/bin/ld: copy_elements.o: undefined reference to symbol 'pthread_condattr_setclock@@GLIBC_2.3.3'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:408: ../planet-dump-ng] Error 1
make[1]: Leaving directory '/usr/local/src/planet-dump-ng-1.2.4/src'
make: *** [Makefile:611: all-recursive] Error 1
```

The versions of the packages installed:
```
autoconf 2.69-14
automake 1:1.16.3-2
libboost-date-time-dev 1.74.0.3
libboost-dev 1.74.0.3
libboost-filesystem-dev 1.74.0.3
libboost-iostreams-dev 1.74.0.3
libboost-program-options-dev 1.74.0.3
libboost-thread-dev 1.74.0.3
build-essential 12.9
libxml2-dev 2.9.10+dfsg-6.7+deb11u2
libosmpbf-dev 1.5.0-1+b1
osmpbf-bin 1.5.0-1+b1
pkg-config 0.29.2-1
libprotobuf-dev 3.12.4-1
```

**Comment by zerebubuth** [comment]
Thanks! I'll have a look as soon as I can.

**Comment by kresp0** [comment]
Hi, tested with 1.2.5 and got the same error. Any suggestions on how to compile it? Should I try to compile on Ubuntu instead?

Making all in src
make[1]: Entering directory '/tmp/planet-dump-ng-1.2.5/src'
  CXX      changeset_filter.o
  CXX      changeset_map.o
  CXX      copy_elements.o
  CXX      dump_archive.o
  CXX      dump_reader.o
  CXX      extract_kv.o
  CXX      history_filter.o
  CXX      insert_kv.o
  CXX      output_writer.o
  CXX      pbf_writer.o
  CXX      planet-dump.o
  CXX      time_epoch.o
  CXX      types.o
  CXX      xml_writer.o
  CXXLD    ../planet-dump-ng
/usr/bin/ld: copy_elements.o: undefined reference to symbol 'pthread_condattr_setclock@@GLIBC_2.3.3'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:408: ../planet-dump-ng] Error 1
make[1]: Leaving directory '/tmp/planet-dump-ng-1.2.5/src'
make: *** [Makefile:611: all-recursive] Error 1

**Comment by mmd-osm** [comment]
pthread isn't included in the linker libs. You can try this one for the time being,

```
./configure LIBS="-lpthread"
```

Then continue with make

**Comment by kresp0** [comment]
That did the trick, thanks!
